// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bzzzecvzoahauqrhkvds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6enplY3Z6b2FoYXVxcmhrdmRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTE2NTYsImV4cCI6MjA3NDI4NzY1Nn0.lKxGWQj9vu18vSpxojBF25IvoujL-1sH3LqUu4SNJcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});